### ISSUE TITLE
Customising remote’s key actions

### ISSUE THREAD

**Issue by paperboyo** [Cathwyler/MagicRemoteService#1]
Hi. Thank you for your work! I wonder if it would be possible to customise some of the keys sent to PC from the Magic Remote (even if only by modifying the code before running it on the PC)?

Let me describe my use case. I would like to be able to control [Plex HTPC](https://support.plex.tv/articles/htpc-getting-started/) PC application using Magic Remote. My PC is connected to the LG TV via HDMI and they are on the same network. Sadly, Plex HTPC doesn’t work well with the PC mouse, but I would like to avoid yet another remote to control the PC. One option would be something like [Flirc](https://forum.kodi.tv/showthread.php?tid=304812).

Your app does the scroll, direction keys, etc. Great! But I would love to be able to have eg. Pause on some of the colour buttons. So, basically, what Windows calls Media Keys, I suppose? I’m not a developer, but maybe I could follow what you did eg. [here](https://github.com/Cathwyler/MagicRemoteService/commit/0406d490b9f6e2880c5c0b020e225765680ad155), if I could find codes for Windows Media Keys?

Sensible/possible? Not possible/stupid?

**Comment by Cathwyler** [comment]
Hi. Thank for your feedback. That's possible and that's a good idea because everyone would have probably some specific use.
That's easy to do but the HMI part will take me a will.
While waiting for a new version if you are able to compile the project with visual studio you can try modify /Resources/TV/MagicRemoteService/main.js

https://github.com/Cathwyler/MagicRemoteService/blob/420528555483091258738e2fcddc09c5d3d6094a/MagicRemoteService/Resources/TV/MagicRemoteService/main.js#L527-L633

Case 0x193 to 0x196 are the color key. refer to https://webostv.developer.lge.com/develop/guides/magic-remote.
The Windows [vk key](https://learn.microsoft.com/fr-fr/windows/win32/inputdev/virtual-key-codes) you need are probably 0xB0 to 0xB3.
You can remap in main.js each case 0x193 to 0x196 in keydown and keyup event with replacing or add
```
case 0x193: //Color key
	...
	break;
```
```
case 0x193: //Color key
	SendKeyboardKey({ 
		usC: 0xB0, //VK Key
		bS: true //true in keydown event false in keyup event
	}); 
```
After compile you need to run it and intall on TV.

**Comment by paperboyo** [comment]
Thanks! Customisation UI would indeed be ideal, but even if the mapping woul exist in a simple config file, that would help a lot (unless the compilation step would be still necessary, which may be too hard to some, like me: although I will try!).

Thanks again!

**Comment by Cathwyler** [comment]
An easier way if Visual Studio compiling is to hard, you can try use CLI. After install on TV you will find the TV App source extracted next to MagicremoteService.exe. You can modify directly ./TV/MagicRemoteService/main.js but don't stroke again install key because ./TV folder will be erased.

Run Windows console (cmd.exe), package and install it with theses commands :

```
ares package "%PathToTVFolder%\MagicRemoteService" -o "%PathToTVFolder%" "%PathToTVFolder%\Send"
ares-install -d "%NAMEOFYOURTV%" ".\TV\com.cathwyler.magicremoteservice.hdmi1_1.1.0_all.ipk"

```

**Comment by Cathwyler** [comment]
You can now change Remote keybind from UI.
