### ISSUE TITLE
Bind "ALT" Key (LEFT ALT) not possible.

### ISSUE THREAD

**Issue by lDeKul** [Cathwyler/MagicRemoteService#19]
Hi,

i have just installed your Software and i wanted to thank you. Its the first out of many "Apps" i tried that truly just works out of the Box and has some great functionality. So i would like to Donate if possible as a "Thank You". If you have a ko-fi Account please let me know.

However i have one issue with the Key-Bindings. I cannot bind the "ALT" (left ALT) Key. I am trying to bind my back Button (REMOTE) to "ALT" + "Arrow Left" i.o. to have it go to the previous Page in Chrome.

If i use the "ALT Graph" + "LEFT ARROW" Keys on my Keyboard, it does work in CHROME. But when i bind the same combo in MRS to the BACK Button it doesn't work. I don't know why the combo would work with the Keyboard but not when bound in the tool.

Would be great if there was a way to bind the "LEFT ALT" + "LEFT ARROW" Key. Or if the "ALT Gr" + "LEFT ARROW" Key would do what it "should" do?

I would really appreciate any Advice in this regard. I have no ideo if this is a WIndows issue.

Thank You again for this great priece of Software...

**Comment by Cathwyler** [comment]
Hi,

Thanks for yous feedback.
Unfortunatly i don't have any donate option, but i will think about it :D.

When i first created the key binding i thought my keyboard's Alt key was broken due to an unfortunate beer accident with my keyboard a long time ago. Surprisingly, it seems that my Alt key works and I have the same bug as you. 

Actually you can't save multiple key or a macro on a binding and i won't do it.
But in your case you only need to save the modifiers keys (Alt, Ctrl, Shift, etc) with the key binding. I will try to add this feature in a future version.

Regards

**Comment by Cathwyler** [comment]
You can try this pre-release [1.2.3.0](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.3.0). I finally added the possibility to set multiple key and fixed the "left ALT" bug

Let me know if it works fine.

**Comment by lDeKul** [comment]
Thank You so much,

it does work now. I had to completely remove the old Version for it to take affect. The Install on TV / Inspect Button usually ends with a failure Message regarding ares-cli but sometimes works. Mostly i just install the *.ipk File in the TV Folder manually. So again thanks a lot.

Regards
