### ISSUE TITLE
Wake-on-LAN not working

### ISSUE THREAD

**Issue by Spottyfriend** [Cathwyler/MagicRemoteService#6]
I have set my PC to work with Wake-on-LAN, and I have tested it with [this app](https://play.google.com/store/apps/details?id=com.bitklog.wolon&hl=en&gl=US) on my phone to make sure the settings are correct, and it works perfectly. However, MagicRemoteService's WOL function does not work for me.

**Comment by Cathwyler** [comment]
To have Wake-on-LAN working you have to set the correct PC MAC adrress in the TVs tab in the PC app.
If you change the MAC adress you need to reinstall the app again on the TV for the change to take effect.
Be careful if you have multiple network card (Wifi, Ethernet, VPN) the MAC address need to match the one who is used to for data exchange between PC and TV.
You can use [Wireshark](https://www.wireshark.org/download.html) to see if you receive or not the Wake-on-LAN message (unplug the HDMI and the TV will think the PC is shut down and you will have access to the startup button. After strike the button, the TV is broadcasting the magic packet every 2 seconds.

Regards,

Cathwyler

**Comment by Peskinator** [comment]
Hi,

I am having the same issue.
I installed Wireshark, started sniffing packets then unplugged the HDMI cable like suggested, to have access to the start button.
I clicked on it, but also used an app on my phone to broadcast the magic packet from another source that is known to work.

As a result, I can see the magic packets sent from my phone, but nothing from the TV's IP address.
Thank you!

**Comment by Cathwyler** [comment]
Can you tell me which webOS sdk version you are running ?

There is probably an error while broadcasting the magick packet.
I just fixed it and i will publish a release tomorow.

Can you check if there is any exception message in the web inspector while broadcasting magick packet ?

**Comment by Peskinator** [comment]
Here are the info:
webOS TV Version: 6.2.1-2414 (on LG C1)
Software Version: 03.25.25

Attached is a screenshot of the console after clicking on "Inspect".
Thanks for your support on this!
![image](https://github.com/Cathwyler/MagicRemoteService/assets/78457941/a14dd987-de94-42b7-a203-2ef963deb92f)

**Comment by Cathwyler** [comment]
There is no error occuring on the TV app. Everything seems normal. And you have a similar TV version than me.
```
ares-device-info -d CATHWYLER-TVSALON -i
modelName : OLED65C15LA
sdkVersion : 6.3.3
firmwareVersion : 03.36.50
```
Its probably a network or a configuration issue. The fact is that your PC is receiving the broadcasting magic packet sent from your smartphone but not from your TV.
Unfortunatly i don't have free time actually to perform some test issues. But i can give you somes workarounds.

One possibility is that you have wifi AND ethernet enabled on your TV and the broadcasting magic packet is sent to the wrong TV network card.

An other possibilty is that your TV is on a guest wifi network and your PC on a private one.

And a third one is that your router is simply blocking broadcasting from your TV because of IDK reason (Not known device, Braodcasting Wifi to Ethernet or Ethernet to Wifi issue, Only fixed IP allowed...).

**Comment by Peskinator** [comment]
Thanks for all your suggestions. This gave me ideas and I continued digging.

Turns out: The magic packet from the TV was not interpreted by Wireshark as a MagicPacket for some reasons.
I fixed it by checking "Try heuristic sub-dissectors first" preference in the UDP section of WireShark. (as mention at the end of https://wiki.wireshark.org/WakeOnLAN ).

Doing this confirmed that when Clicking on the Start button (After unplugging the HDMI Cable), does work, and is indeed starting my computer.

So in fact the problem is that the Magic packet is only sent in this scenario (TV is ON, then I unplug the cable, then I press start).
Its not sent when starting the TV, and it's not sent when pushing the red button on the remote.

Does those conclusions make sense ?

Thanks again for since amazing tool !

**Comment by Peskinator** [comment]
After even more digging, I finally know what was the problem:

My TV is not directly plugged to my PC, but through a Soundbar.  (PC--HDMI-->Soundbar--HDMI-->TV).
So when the TV starts with the computer being off, I don't see the popup with the Start button because the app detects that something is plugged to the input: The soundbar. So I don't have the opportunity to send the magic packet. I see another popup saying something the PC cannot be detected, but no Start button.

If I plug the TV to the PC directly (bypassing my soundbar) everything works as you designed it.

Unfortunately I can't change my setup because the soundbar works way better like this for PC gaming and DTS Movies.

Would it be possible to display the Start button in the other popups as well? 
Maybe there are other solutions but so far i can only think of this one.

**Comment by Cathwyler** [comment]
That’s what I was going to suggest. At the beginning, you don’t see the start-up dialog. 
The app think the PC is booting and that's why you don't see the start-up dialog. After 30 seconds an error connection dialog appears.

I will add an option to circumvent this mechanism in the case of indirect plugging.

Regards

**Comment by Cathwyler** [comment]
You can try this pre-release [1.2.3.0](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.3.0). I added a direct HDMI wiring option. You need to uncheck it and install on TV.

Let me know if it works fine.

**Comment by Peskinator** [comment]
Thanks!
It works!! 
That's exactly what I needed :)
