### ISSUE TITLE
Can't make it work with 49UJ6307

### ISSUE THREAD

**Issue by marcijel1** [Cathwyler/MagicRemoteService#7]
It looks everything is OK, I didn't get any error messages during the installation, but the magic remote is not controlling my PC mouse.
they are on the same LAN.
PC OS: W10
The settings:
![kép](https://github.com/Cathwyler/MagicRemoteService/assets/99387431/10530323-1683-4748-9822-9b9c143e9728)

Also I tried with the default settings, without changing anything, or with the default port what the program gives (maybe 43210?) and with the correct LAN IP. Or changing the values during ["Connecting with CLI"](https://webostv.developer.lge.com/develop/getting-started/developer-mode-app#connecting-with-cli) .
But yes, they can connect (webos CLI and PC), `ares-device-info --device tv2` says the right informations about the tv. So the error should be with my settings in MagicRemoteService? After I click to the `Install on TV` button, the TV screen is going black (with a white rectangle on the upper left corner ~it is something new app on the TV, I can choose it from the app menu, magicremoteserice, but it can't show my desktop, and also if I change back to HDMI1, it can't control the mouse), and the PC program turns inactive for a few seconds... then nothing happens, no errors.

What settings are wrong? Or is my TV too old for this program?

Thank you for the help.

**Comment by Cathwyler** [comment]
Hi,

Everything is correct except the port number. The port 9922 is already used by the WebOS CLI, so you need to choose another one free and put the same in the TV tab and PC tab. Once you have done it you need to reinstall in TV tab and also resave on PC tab for the change to take effect.

The issue "white rectangle in the upper left corner" happens when the TV app an exception occurs during the loading. I just fixed it with the 1.2.0.2 release for webOS 4.x. Unfortunately you have a webOs 3.x version and i don't have the possiblity to debug it yet with older webOS version. Please see this [issue](https://github.com/Cathwyler/MagicRemoteService/issues/4) for more information. However, i think i can test 2 or 3 things. So i will come back with a new version (dunno when) and you will need to test it (dunno when but i will post new message in this thread when it be available).

Regards,

Cathwyler

**Comment by Cathwyler** [comment]
Hi,

I just found a 38 Chromium version used in webOS 3.x and i fixed some exception.
Please give a try at this new release [1.2.0.3](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.0.3). Let me know if the app is now working on your TV.

For changes to take effect, you need to reinstall the TV app. Be careful while updating MagicRemoteService on the PC if you have "Automatically launch at startup" option checked or older executable file version running. You need to stop MagicRemoteService on your Windows service or any running instance and replace the executable file. Otherwise there is a chance, due to the unique allowed running instance and even if you launch a new version, to keep an older MagicRemoteVersion running.

Hope it will work :).
Regards,

Cathwyler

**Comment by marcijel1** [comment]
WOOOOOW, You're amazing. It's working.

There is an other issue. The TV is showing an error message:
![signal-2023-09-20-201456](https://github.com/Cathwyler/MagicRemoteService/assets/99387431/74785384-c8b7-4814-9895-130344291ac6)
`Failed to send key [{}]@PC.IP:PORT {"usC":1537."bS":true}`
It disappears after I click on it with the magic remote, but reappears after every click.
But the mouse functions are ~100% working (I tested only the left-right click and scroll).

But maybe I just have some issues with multiple instances and other shitty things.
I don't have an HDMI cable now, and I'm far from the TV, so I can't test it further for a while.

Thank you for the help.

**Comment by Cathwyler** [comment]
Thanks,

I fixed on more bug [1.2.0.4](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.0.4).

Let me know if everything is ok (or not) :).
Regards,

Cathwyler
