### ISSUE TITLE
Selecting PC Display

### ISSUE THREAD

**Issue by Jolima** [Cathwyler/MagicRemoteService#9]
Hi, I just tried installing this and it seems to work great when I set the TV to be my primary display, but when I don't it just moves the mouse on my computer screen instead of the TV. Is there some option I'm missing for that or is it something you could add support for? Either selecting which display it should be or maybe even auto detecting which of them is a TV.

Thanks for making and sharing it.

**Comment by Jolima** [comment]
I looked into it a little myself, and this looks like it contains most of how to do this after picking a monitor (C++ rather than C# though): https://stackoverflow.com/questions/62759122/calculate-normalized-coordinates-for-sendinput-in-a-multi-monitor-environment

In short use MOUSEEVENTF_VIRTUALDESK and convert positions within the screen to positions in the whole virtual desktop.

**Comment by Cathwyler** [comment]
Hi,

I can add a display selector like i did for the HMDI input selector.
I will try to do it this weekend or the next one if i have free time to kill.
But i wil not do the ability to select the Window screen number on TV app, because i consider like HDMI input that is static parameter and how your displays are wired.

There is the [Screen Classe](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.screen?view=windowsdesktop-7.0&redirectedfrom=MSDN) doing it well in .Net.

On my side, i never use the screen computer and the TV simultaneously. When i use a TV or a screen computer, i managed that they are always set to "primary screen" in Windows configuration. 
When i use my TV, i electricaly shutdown (not standby) my screen computer with the electrical switch. So the TV switch to primary.
This is working because Windows is storing in the registry the screen configuration depending on wich displays are wired or electricaly turned on.

Regards

**Comment by Cathwyler** [comment]
Hi,

You can now select a TV screen in the TV tab on PC app.

Give a try at this new release [1.2.2.0](https://github.com/Cathwyler/MagicRemoteService/releases/tag/1.2.2.0)
Let me know if it work as intended.

Regards,

**Comment by Jolima** [comment]
Can confirm that it works. Thanks for adding it.
